# Adapted from
# - https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder/blob/main/docker-compose.yml
# - https://sdr-enthusiasts.gitbook.io/ads-b/foundations/deploy-ultrafeeder-container
# - https://sdr-enthusiasts.gitbook.io/ads-b/feeder-containers/feeding-flightradar24
# - https://sdr-enthusiasts.gitbook.io/ads-b/feeder-containers/feeding-flightaware-piaware

services:
  rtlsdr-ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
    # Note - if you want to enable telegraf for use with InfluxDB/Prometheus and Grafana,
    # use the following image instead:
    # image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder:telegraf
    container_name: rtlsdr-ultrafeeder
    hostname: rtlsdr-ultrafeeder
    restart: unless-stopped
    device_cgroup_rules:
      - "c 189:* rwm"
    ports:
      - 8000:80 # to expose the web interface
      # - 9273-9274:9273-9274 # to expose the statistics interface to Prometheus
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=${LOGLEVEL-verbose}
      - TZ=${FEEDER_TZ}
      # --------------------------------------------------
      # SDR related parameters:
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_GAIN=auto
      - READSB_RTLSDR_DEVICE=${ADSB_SDR_SERIAL}
      - READSB_RTLSDR_PPM=${ADSB_SDR_PPM}
      #
      # --------------------------------------------------
      # readsb/decoder parameters:
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_ALT=${FEEDER_ALT_M}m
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      #
      # --------------------------------------------------
      # Sources and Aggregator connections:
      # Notes - remove the ones you are not using / feeding
      #       - remove "adsb,dump978,30978,uat_in;" if you don't have dump978 and a UAT dongle connected to your station
      #       - !!! make sure that each line ends with a semicolon ";",  with the exception of the last line which shouldn't have a ";" !!!
      - ULTRAFEEDER_CONFIG=
        adsb,feed.adsb.fi,30004,beast_reduce_plus_out,uuid=${ADSBFI_UUID};
        mlat,feed.adsb.fi,31090,uuid=${ADSBFI_UUID};
        adsb,in.adsb.lol,30004,beast_reduce_plus_out,uuid=${ADSBLOL_UUID};
        mlat,in.adsb.lol,31090,uuid=${ADSBLOL_UUID};
        adsb,feed.airplanes.live,30004,beast_reduce_plus_out,uuid=${AIRPLANESLIVE_UUID};
        mlat,feed.airplanes.live,31090,uuid=${AIRPLANESLIVE_UUID};
        adsb,feed.planespotters.net,30004,beast_reduce_plus_out,uuid=${PLANESPOTTERS_UUID};
        mlat,mlat.planespotters.net,31090,uuid=${PLANESPOTTERS_UUID};
        adsb,feed.theairtraffic.com,30004,beast_reduce_plus_out,uuid=${THEAIRTRAFFIC_UUID};
        mlat,feed.theairtraffic.com,31090,uuid=${THEAIRTRAFFIC_UUID};
        adsb,data.avdelphi.com,24999,beast_reduce_plus_out,uuid=${AVDELPHI_UUID};
        adsb,dati.flyitalyadsb.com,4905,beast_reduce_plus_out,uuid=${FLYITALYADSB_UUID};
        mlat,dati.flyitalyadsb.com,30100,uuid=${FLYITALYADSB_UUID}
      # If you really want to feed ADSBExchange, you can do so by adding this above:
      #        adsb,feed1.adsbexchange.com,30004,beast_reduce_plus_out,uuid=${ADSBX_UUID};
      #        mlat,feed.adsbexchange.com,31090,39008,uuid=${ADSBX_UUID}
      #
      # --------------------------------------------------
      - UUID=${FEEDER_UUID}
      - MLAT_USER=${FEEDER_NAME}
      #
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=true
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${FEEDER_NAME}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=2.0
      - TAR1090_RANGERINGSDISTANCES=50,100,150,200
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      - TAR1090_USEROUTEAPI=true
      #
      # --------------------------------------------------
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_DARKMODE=true
      # - ENABLE_978=yes
      # - URL_978=http://rtlsdr-dump978/skyaware978
      #
      # --------------------------------------------------
      # Prometheus and InfluxDB connection parameters:
      # (See above for the correct image tag you must use to enable this)
      # - INFLUXDBV2_URL=${INFLUX_URL}
      # - INFLUXDBV2_TOKEN=${INFLUX_TOKEN}
      # - INFLUXDBV2_BUCKET=${INFLUX_BUCKET}
      # - PROMETHEUS_ENABLE=true
    volumes:
      - /data/rtlsdr/ultrafeeder/globe_history:/var/globe_history
      - /data/rtlsdr/ultrafeeder/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev/bus/usb:/dev/bus/usb
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
  
  rtlsdr-feed-fr24:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
    container_name: rtlsdr-feed-fr24
    restart: always
    ports:
      - 8001:8754
    environment:
      - BEASTHOST=rtlsdr-ultrafeeder
      - FR24KEY=${FR24_SHARING_KEY}
    dns_search: . # prevents rare connection issues related to a bug in docker and fr24feed
    tmpfs:
      - /var/log:size=16M
  
  # FlightAware
  rtlsdr-feed-piaware:
    image: ghcr.io/sdr-enthusiasts/docker-piaware:latest
    container_name: rtlsdr-feed-piaware
    restart: unless-stopped
    ports:
      - 8002:8080
    environment:
      - BEASTHOST=rtlsdr-ultrafeeder
      - MLAT_RESULTS_BEASTHOST=rtlsdr-ultrafeeder
      - MLAT_RESULTS_BEASTPORT=31004
      - TZ=${FEEDER_TZ}
      - FEEDER_ID=${PIAWARE_FEEDER_ID}
    tmpfs:
      - /run:exec,size=64M
      - /var/log:size=16M
