# Adapted from:
# - https://jellyfin.org/docs/general/installation/container

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: 1001:1001
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - type: bind
        source: /data/jellyfin/media
        target: /media
